# Generated by Django 6.0.2 on 2026-02-24 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_genre_options_artist_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_position', models.IntegerField(default=0)),
                ('duration_listened', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('session_id', models.UUIDField(unique=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='listeninghistory',
            name='app_listeni_user_id_a025c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='listeninghistory',
            name='app_listeni_track_i_2d8900_idx',
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_session', to='app.track'),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='listeninghistory',
            name='track',
        ),
        migrations.RemoveField(
            model_name='listeninghistory',
            name='user',
        ),
        migrations.AddIndex(
            model_name='listeningsession',
            index=models.Index(fields=['user', '-started_at'], name='app_listeni_user_id_10d620_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningsession',
            index=models.Index(fields=['track'], name='app_listeni_track_i_d8f7b7_idx'),
        ),
        migrations.DeleteModel(
            name='ListeningHistory',
        ),
    ]
