# Generated by Django 6.0.2 on 2026-02-24 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_listeningsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
