# Generated by Django 6.0.2 on 2026-02-26 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_listeningsession_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listeningsession',
            name='app_listeni_user_id_10d620_idx',
        ),
        migrations.RemoveIndex(
            model_name='listeningsession',
            name='app_listeni_track_i_d8f7b7_idx',
        ),
        migrations.AddIndex(
            model_name='listeningsession',
            index=models.Index(fields=['user', 'track'], name='app_listeni_user_id_05ca1f_idx'),
        ),
    ]
